// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHh5cyU-ochWIgS6SDsNQjDgfEiyjNYNU',
    appId: '1:90041522201:android:3bf7d9b0e0ea006f73b288',
    messagingSenderId: '90041522201',
    projectId: 'grocygo-c9820',
    databaseURL: 'https://grocygo-c9820-default-rtdb.firebaseio.com',
    storageBucket: 'grocygo-c9820.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfJLcf7BHCyeVheFdfXePmmsrEeCRPG-k',
    appId: '1:90041522201:ios:e7ed1fc7af0cd22573b288',
    messagingSenderId: '90041522201',
    projectId: 'grocygo-c9820',
    databaseURL: 'https://grocygo-c9820-default-rtdb.firebaseio.com',
    storageBucket: 'grocygo-c9820.firebasestorage.app',
    iosBundleId: 'com.example.grocygo',
  );
}
